
##################################################################
#
#  Author:  Rob Hurst
# 
#  Date:    March 2016
# 
#  This code reads human activity data generated by smartphones
#  and generates a tidy dataset for downstream processing.
#
##################################################################


# packages
library(data.table)
library(plyr)





# Check if directory exists, and create it if it doesn't
  if(!file.exists("UCI HAR Dataset")){         
    dir.create("UCI HAR Dataset")
  }

  
# Download the zipped dataset
    fileUrl<-"https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
  download.file(fileUrl, destfile = "./UCI HAR Dataset.zip", method ="curl")
  dateDownloaded<-date()

# Load files to R from the downloaded zip file
  X_test<-read.table("./UCI HAR Dataset/test/X_test.txt")
  y_test<-read.table("./UCI HAR Dataset/test/y_test.txt")
  subject_test<-read.table("./UCI HAR Dataset/test/subject_test.txt")
  X_train<-read.table("./UCI HAR Dataset/train/X_train.txt")
  y_train<-read.table("./UCI HAR Dataset/train/y_train.txt")
  subject_train<-read.table("./UCI HAR Dataset/train/subject_train.txt")
  features<-read.table("./UCI HAR Dataset/features.txt")
  activity<-read.table("./UCI HAR Dataset/activity_labels.txt")
  
  
  
#Check to make sure the data has loaded correctly
  nrow(X_test)
  nrow(y_test)
  nrow(subject_test)
  nrow(X_train)
  nrow(y_train)
  nrow(subject_train)
  nrow(features)
  nrow(activity)
  
  
# Bind the test and train datasets
  All_x <- rbind(X_test,X_train)
  All_y <- rbind(y_test,y_train)
  Subject <- rbind(subject_test,subject_train)

  
# Get the indexes of the features that include "mean()" or "std()"   
  Features_inc<-grep("-mean()|-std()",features[,2])
  
  
# Name the column in the subjectID data frame
  colnames(subjectID)<-"SubID"
  
# Merge activity label data with Y
  All_y<-join(All_y,activity)
  All_y2<-All_y[,2]
  All_y2<-data.frame(All_y2)
  colnames(All_y2)<-"Activity_Label"
  
  
  
# Limit the x data to the maen and std features and Label the X data
  All_x <- All_x[,Features_inc]
  names(All_x) <- gsub("(|)","",features$V2[Features_inc])
  
# cbind all of the data
  Alldata<-cbind(subjectID,All_x,All_y2)
  write.table(Alldata,"merged_Alldata.txt")
  
# Calculate mean and standard deviation
  TidyData<-data.table(Alldata)
  MeanSD<-TidyData[,lapply(.SD,mean), by=c("SubID","Activity_Label")]
  write.table(MeanSD,"MeanSD_Tidy_Data.txt", row.name=FALSE)



  
  
  
  